// Theme list
const FETCH_THEMES = 'FETCH_THEMES';
const FETCH_THEMES_SUCCESS = 'FETCH_THEMES_SUCCESS';
const FETCH_THEMES_FAILURE = 'FETCH_THEMES_FAILURE';
const RESET_THEMES = 'RESET_THEMES';

const PUBLISH_THEME = 'PUBLISH_THEME';
const PUBLISH_THEME_SUCCESS = 'PUBLISH_THEME_SUCCESS';
const PUBLISH_THEME_FAILURE = 'PUBLISH_THEME_FAILURE';

export default {
  FETCH_THEMES,
  FETCH_THEMES_SUCCESS,
  FETCH_THEMES_FAILURE,
  RESET_THEMES,
  PUBLISH_THEME,
  PUBLISH_THEME_SUCCESS,
  PUBLISH_THEME_FAILURE
};
